### ISSUE TITLE
Functionality to manually enter quote doesn't work

### ISSUE THREAD

**Issue by RalphORama** [RalphORama/QuoteBot#10]
After pull #9 functionality for entering quotes manually doesn't work.

```
Encountered error in quote comand:
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ralph/.virtualenvs/QuoteBot/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ralph/Documents/Discord-Bots/QuoteBot/cogs/quote.py", line 103, in quote
    user_id = int("".join(filter(str.isdigit, msg_ids[1])))
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ralph/.virtualenvs/QuoteBot/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "/home/ralph/.virtualenvs/QuoteBot/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 943, in on_message
    await self.process_commands(message)
  File "/home/ralph/.virtualenvs/QuoteBot/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 940, in process_commands
    await self.invoke(ctx)
  File "/home/ralph/.virtualenvs/QuoteBot/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 907, in invoke
    await ctx.command.dispatch_error(ctx, exc)
  File "/home/ralph/.virtualenvs/QuoteBot/lib/python3.8/site-packages/discord/ext/commands/core.py", line 422, in dispatch_error
    await injected(cog, ctx, error)
  File "/home/ralph/.virtualenvs/QuoteBot/lib/python3.8/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ralph/Documents/Discord-Bots/QuoteBot/cogs/quote.py", line 210, in quote_error_handler
    raise error
  File "/home/ralph/.virtualenvs/QuoteBot/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ralph/.virtualenvs/QuoteBot/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1334, in invoke
    await super().invoke(ctx)
  File "/home/ralph/.virtualenvs/QuoteBot/lib/python3.8/site-packages/discord/ext/commands/core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ralph/.virtualenvs/QuoteBot/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: invalid literal for int() with base 10: ''
```

**Comment by RalphORama** [comment]
@DakotaWorzella any interest in working on this?

**Comment by DakotaWorzella** [comment]
What was the command that you had used that gave the issue

**Comment by DakotaWorzella** [comment]
> 
> 
> @DakotaWorzella any interest in working on this?

Could you right down what you did that produced that error?

**Comment by RalphORama** [comment]
The commands I tried were:

```
@QuoteBot quote @RalphORama this is a test quote!
```

and

```
@QuoteBot quote this is a test quote!
```

**Comment by DakotaWorzella** [comment]
The way I did it is @QuoteBot quote "this is a test quote!" @RalphORama

**Comment by DakotaWorzella** [comment]
If you wanted to swap them around, go ahead
